"""add details to ops_alerts

Revision ID: 904485e416d8
Revises: f2243da90c2a
Create Date: 2026-05-07 20:10:06.278830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '904485e416d8'
down_revision = 'f2243da90c2a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_predictions_id'), 'anomaly_predictions', ['id'], unique=False)
    op.drop_index('ix_predictions_id', table_name='predictions')
    op.drop_table('predictions')
    op.add_column('ops_alerts', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ops_alerts', 'details')
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='predictions_pkey')
    )
    op.create_index('ix_predictions_id', 'predictions', ['id'], unique=False)
    op.drop_index(op.f('ix_anomaly_predictions_id'), table_name='anomaly_predictions')
    op.drop_table('anomaly_predictions')
    # ### end Alembic commands ###