global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: mediflow_backend
    static_configs:
      - targets:
          - backend:8000
          - api:8000
    metrics_path: /metrics

  - job_name: mediflow_ml
    static_configs:
      - targets:
          - ml_service:8001
    metrics_path: /metrics